# Generated by Django 5.0.6 on 2024-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='banner',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
