# Generated by Django 5.0.6 on 2024-05-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_listing_category_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='banner',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
