# Generated by Django 5.0.6 on 2024-05-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
