# Generated by Django 5.0.6 on 2024-05-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
