# Generated by Django 5.0.6 on 2024-05-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
